# # Use the official Python image
# FROM python:3.9-slim

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the requirements.txt file from the parent directory
# COPY ../requirements.txt /app/requirements.txt

# # Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy the entire ITP_WEBAPP directory into the container
# COPY . /app/

# # Set environment variables
# ENV PYTHONUNBUFFERED=1

# # Expose the port Django will run on
# EXPOSE 8000

# # Run the Django application
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
